import React, { useEffect, useState } from 'react';
import type { Employee, EmployeeInput, OcrProgress, Project } from '../../shared/types';
import { AssetImage, ImageSlot } from './Images';
import { Confirm, Empty, Field, LoadState, Modal, Select, TextArea, localDate, matches, type Notify, useResource, useTask } from './ui';
const blank: EmployeeInput={fullName:'',birthDate:'',identityNumber:'',issueDate:'',permanentAddress:'',projectId:'',portraitId:null,idFrontId:null,idBackId:null,notes:''};
const asInput=(e:Employee):EmployeeInput=>({id:e.id,fullName:e.fullName,birthDate:e.birthDate,identityNumber:e.identityNumber,issueDate:e.issueDate,permanentAddress:e.permanentAddress,projectId:e.projectId,portraitId:e.portraitId,idFrontId:e.idFrontId,idBackId:e.idBackId,notes:e.notes,archived:e.archived});
export default function Employees({notify}: {notify:Notify}) {
 const [search,setSearch]=useState(''); const [projectId,setProjectId]=useState('');const [archiveFilter,setArchiveFilter]=useState('active');
 const projects=useResource(()=>window.thean.projects.list(true),notify);
 const employees=useResource(()=>window.thean.employees.list({projectId:projectId||undefined,search:search||undefined,includeArchived:archiveFilter!=='active'}),notify,[projectId,search,archiveFilter]);
 const [draft,setDraft]=useState<EmployeeInput|null>(null); const [archive,setArchive]=useState<Employee|null>(null); const {busy,run}=useTask(notify);
 const visible=employees.data?.filter(e=>matches(`${e.fullName} ${e.identityNumber}`,search)&&(archiveFilter==='all'||(archiveFilter==='archived'?e.archived:!e.archived)));
 return <><header className="page-head"><div><p className="eyebrow">HỒ SƠ NHÂN SỰ</p><h1>Nhân viên</h1><p>Thông tin, ảnh căn cước và lịch sử làm việc trong một hồ sơ.</p></div><button className="primary" onClick={()=>setDraft({...blank,projectId:projectId&&projects.data?.some(p=>p.id===projectId&&!p.archived)?projectId:''})}>Thêm nhân viên</button></header>
 <div className="card filters"><Field label="Tìm nhân viên" type="search" placeholder="Họ tên hoặc số căn cước" value={search} onChange={e=>setSearch(e.target.value)}/><Select label="Lọc dự án" value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">Tất cả dự án</option>{projects.data?.map(p=><option key={p.id} value={p.id}>{p.name}{p.archived?' (lưu trữ)':''}</option>)}</Select><Select label="Trạng thái hồ sơ" value={archiveFilter} onChange={e=>setArchiveFilter(e.target.value)}><option value="active">Đang hoạt động</option><option value="archived">Đã lưu trữ</option><option value="all">Tất cả hồ sơ</option></Select></div>
 <LoadState {...employees} retry={employees.reload}/><LoadState loading={false} error={projects.error} retry={projects.reload}/>
 {!employees.loading&&!employees.error&&visible?.length===0&&<Empty title="Chưa có nhân viên phù hợp">Thêm hồ sơ mới hoặc thay đổi bộ lọc để tìm nhân viên.</Empty>}
 {!!visible?.length&&<div className="card table-wrap"><table><thead><tr><th>Nhân viên</th><th>Căn cước</th><th>Dự án hiện tại</th><th>Trạng thái</th><th><span className="sr-only">Thao tác</span></th></tr></thead><tbody>{visible.map(e=><tr key={e.id}><td><div className="person-cell"><AssetImage id={e.portraitId} alt={`Ảnh ${e.fullName}`} className="avatar"/><div><button className="text-button person-name" aria-label={`Mở hồ sơ ${e.fullName}`} onClick={()=>setDraft(asInput(e))}>{e.fullName||'Chưa ghi họ tên'}</button><small>{e.birthDate||'Chưa ghi ngày sinh'}</small></div></div></td><td className="code">{e.identityNumber||'—'}</td><td>{e.projectName||'Chưa có dự án'}</td><td><span className={`badge ${e.archived?'':'green'}`}>{e.archived?'Lưu trữ':'Hoạt động'}</span></td><td><button disabled={busy} onClick={()=>setArchive(e)}>{e.archived?'Khôi phục':'Lưu trữ'}</button></td></tr>)}</tbody></table><footer className="table-footer">{visible.length} hồ sơ</footer></div>}
 {draft&&<EmployeeForm initial={draft} projects={projects.data??[]} notify={notify} onClose={()=>setDraft(null)} onSaved={()=>{setDraft(null);employees.reload();projects.reload();}} onTransferred={employees.reload}/>}
 {archive&&<Confirm title={archive.archived?'Khôi phục hồ sơ':'Lưu trữ hồ sơ'} busy={busy} onClose={()=>setArchive(null)} action={archive.archived?'Xác nhận khôi phục':'Xác nhận lưu trữ'} onConfirm={()=>void run(async()=>{await window.thean.employees.archive(archive.id,!archive.archived);setArchive(null);employees.reload();projects.reload();notify(archive.archived?'Đã khôi phục hồ sơ.':'Đã lưu trữ hồ sơ.');})}><p><strong>{archive.fullName}</strong>: {archive.archived?'hồ sơ sẽ trở lại danh sách nhân viên hoạt động.':'hồ sơ được giữ lại và ẩn khỏi danh sách hoạt động.'}</p></Confirm>}
 </>;
}
function EmployeeForm({initial,projects,notify,onClose,onSaved,onTransferred}: {initial:EmployeeInput;projects:Project[];notify:Notify;onClose:()=>void;onSaved:()=>void;onTransferred:()=>void}) {
 const [draft,setDraft]=useState(initial);const [warnings,setWarnings]=useState<string[]>([]);const [ocrBusy,setOcrBusy]=useState(false);const [progress,setProgress]=useState<OcrProgress>({status:'Đang chuẩn bị đọc ảnh…',progress:0});
 const [transfer,setTransfer]=useState(false);const [imageBusy,setImageBusy]=useState<Record<string,boolean>>({});const {busy,run}=useTask(notify);const [historyRevision,setHistoryRevision]=useState(0);
 const history=useResource(()=>draft.id?window.thean.employees.history(draft.id):Promise.resolve([]),notify,[draft.id,historyRevision]);
 const imageLoading=Object.values(imageBusy).some(Boolean);const locked=busy||ocrBusy||imageLoading;
 const change=(key:keyof EmployeeInput,value:string|null)=>setDraft(d=>({...d,[key]:value}));
 const unsubscribeRef=React.useRef<(()=>void)|null>(null);useEffect(()=>()=>unsubscribeRef.current?.(),[]);
 const readOcr=async()=>{if(locked)return;const images=[draft.idFrontId,draft.idBackId].filter((id):id is string=>!!id);if(!images.length){setWarnings(['Vui lòng tải ít nhất một ảnh căn cước trước khi đọc.']);return;}setOcrBusy(true);setWarnings([]);setProgress({status:'Đang chuẩn bị đọc ảnh căn cước…',progress:0});
 try {unsubscribeRef.current=window.thean.ocr.onProgress(p=>setProgress({status:p.status,progress:Math.min(1,Math.max(0,p.progress))}));const result=await window.thean.ocr.recognize(images);const keys=['fullName','birthDate','identityNumber','issueDate','permanentAddress'] as const;
 setDraft(current=>{const next={...current};for(const key of keys){const value=result.fields[key];if(typeof value==='string'&&value.trim())next[key]=value.trim();}return next;});
 const filled=keys.filter(key=>result.fields[key]?.trim());const missing=keys.filter(key=>!result.fields[key]?.trim());const labels={fullName:'họ tên',birthDate:'ngày sinh',identityNumber:'số căn cước',issueDate:'ngày cấp',permanentAddress:'hộ khẩu thường trú'};
 setWarnings([...result.warnings,...(!filled.length?['Không đọc được thông tin từ ảnh. Bạn có thể nhập thủ công hoặc tải ảnh rõ hơn.']:missing.length?[`Chưa đọc được: ${missing.map(key=>labels[key]).join(', ')}. Giá trị đã nhập được giữ nguyên.`]:[])]);
 if(filled.length)notify('Đã điền thông tin đọc được. Vui lòng kiểm tra và chỉnh sửa nếu cần.');
 }catch(e){notify(e instanceof Error?e.message:'Không đọc được căn cước. Vui lòng thử lại.',true);}finally{unsubscribeRef.current?.();unsubscribeRef.current=null;setOcrBusy(false);}};
 return <Modal title={draft.id?'Hồ sơ nhân viên':'Thêm nhân viên'} onClose={onClose} busy={locked} wide><form onSubmit={e=>{e.preventDefault();if(locked)return;void run(async()=>{await window.thean.employees.save({...draft,fullName:draft.fullName.trim(),identityNumber:draft.identityNumber.trim()});notify('Đã lưu hồ sơ.');onSaved();});}}><div className="modal-body employee-layout"><div className="employee-main"><h3 className="section-title">Thông tin cá nhân</h3><p className="muted">Mọi trường đều có thể chỉnh sửa. Thông tin căn cước chưa đọc được cần nhập thủ công.</p><fieldset disabled={busy}><div className="form-grid"><div className="span-2"><Field label="Họ và tên" required maxLength={200} placeholder="Ví dụ: NGUYỄN VĂN AN" value={draft.fullName} onChange={e=>change('fullName',e.target.value)}/></div><Field label="Ngày sinh" type="date" value={draft.birthDate} onChange={e=>change('birthDate',e.target.value)}/><Field label="Số căn cước" inputMode="numeric" placeholder="12 chữ số trên thẻ CCCD" value={draft.identityNumber} onChange={e=>change('identityNumber',e.target.value)}/><Field label="Ngày cấp" type="date" value={draft.issueDate} onChange={e=>change('issueDate',e.target.value)}/>{!draft.id?<Select label="Dự án hiện tại" required value={draft.projectId} onChange={e=>change('projectId',e.target.value)}><option value="">Chọn dự án</option>{projects.filter(p=>!p.archived).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</Select>:<div className="field"><span>Dự án hiện tại</span><div className="current-project"><span>{projects.find(p=>p.id===draft.projectId)?.name||'Chưa có dự án'}</span><button type="button" disabled={locked} onClick={()=>setTransfer(true)}>Chuyển dự án</button></div></div>}<div className="span-2"><TextArea label="Hộ khẩu thường trú" placeholder="Địa chỉ thường trú ghi trên thẻ CCCD…" value={draft.permanentAddress} onChange={e=>change('permanentAddress',e.target.value)}/></div><div className="span-2"><TextArea label="Ghi chú hồ sơ" placeholder="Ghi chú thêm về nhân viên (không bắt buộc)…" value={draft.notes} onChange={e=>change('notes',e.target.value)}/></div></div></fieldset>
 <section className="ocr-panel"><div className="between"><div><h3>Đọc thông tin căn cước</h3><p className="muted">Có thể đọc một hoặc hai mặt. Hộ khẩu thường trú được điền trực tiếp.</p></div><button type="button" disabled={locked} onClick={()=>void readOcr()}>{ocrBusy?'Đang đọc…':'Đọc căn cước'}</button></div>{ocrBusy&&<div role="status"><p>{progress.status}</p><progress max={1} value={progress.progress} aria-label="Tiến độ đọc căn cước"/></div>}{warnings.length>0&&<div className="notice" role="status"><ul>{warnings.map((w,i)=><li key={i}>{w}</li>)}</ul></div>}</section>
 {draft.id&&<section className="history"><h3>Lịch sử dự án</h3><LoadState {...history} retry={history.reload}/>{history.data?.length===0&&!history.loading&&<p className="muted">Chưa có lịch sử phân công.</p>}{history.data?.map(a=><div className="history-row" key={a.id}><strong>{a.projectName}</strong><span><time>{a.startDate}</time> → {a.endDate||'Hiện tại'}</span></div>)}</section>}</div>
 <aside className="employee-images"><ImageSlot label="Ảnh chân dung" kind="portrait" id={draft.portraitId} onChange={id=>change('portraitId',id)} notify={notify} disabled={locked} onBusy={b=>setImageBusy(s=>({...s,portrait:b}))}/><p className="muted small">Ảnh chân dung được tải riêng để dùng trong lý lịch.</p><ImageSlot label="Mặt trước căn cước" kind="idFront" id={draft.idFrontId} onChange={id=>change('idFrontId',id)} notify={notify} disabled={locked} onBusy={b=>setImageBusy(s=>({...s,front:b}))}/><ImageSlot label="Mặt sau căn cước" kind="idBack" id={draft.idBackId} onChange={id=>change('idBackId',id)} notify={notify} disabled={locked} onBusy={b=>setImageBusy(s=>({...s,back:b}))}/></aside></div><footer className="actions"><span className="muted action-note">Lưu hồ sơ để giữ các thay đổi.</span><button type="button" onClick={onClose} disabled={locked}>Đóng</button><button className="primary" disabled={locked}>{busy?'Đang lưu…':'Lưu hồ sơ'}</button></footer></form>
 {transfer&&draft.id&&<Transfer employeeId={draft.id} currentProjectId={draft.projectId} projects={projects} notify={notify} onClose={()=>setTransfer(false)} onSaved={newProjectId=>{setDraft(d=>({...d,projectId:newProjectId}));setTransfer(false);setHistoryRevision(v=>v+1);onTransferred();}}/>}</Modal>;
}
function Transfer({employeeId,currentProjectId,projects,notify,onClose,onSaved}: {employeeId:string;currentProjectId:string;projects:Project[];notify:Notify;onClose:()=>void;onSaved:(id:string)=>void}) {
 const [projectId,setProjectId]=useState('');const [date,setDate]=useState(localDate);const {busy,run}=useTask(notify);
 return <Modal title="Chuyển dự án" onClose={onClose} busy={busy}><form onSubmit={e=>{e.preventDefault();void run(async()=>{await window.thean.employees.transfer(employeeId,projectId,date);notify('Đã chuyển dự án và cập nhật lịch sử.');onSaved(projectId);});}}><fieldset disabled={busy}><div className="modal-body"><p>Chọn nơi làm việc mới và ngày bắt đầu. Lịch sử phân công được giữ lại.</p><Select label="Dự án mới" required value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">Chọn dự án mới</option>{projects.filter(p=>!p.archived&&p.id!==currentProjectId).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</Select><Field label="Ngày bắt đầu" required type="date" value={date} onChange={e=>setDate(e.target.value)}/></div><footer className="actions"><button type="button" onClick={onClose}>Hủy</button><button className="primary" disabled={!projectId||!date}>{busy?'Đang chuyển…':'Xác nhận chuyển'}</button></footer></fieldset></form></Modal>;
}
