import React, { useEffect, useRef, useState } from 'react';
import type { Employee, ExportPreview } from '../../shared/types';
import { Confirm, Empty, Field, LoadState, Select, localDate, matches, type Notify, useResource, useTask } from './ui';
export function missingFields(e:Employee) {return ([['fullName','họ tên'],['birthDate','ngày sinh'],['identityNumber','số căn cước'],['issueDate','ngày cấp'],['permanentAddress','hộ khẩu thường trú'],['portraitId','ảnh chân dung']] as const).filter(([key])=>!e[key]?.trim()).map(([,label])=>label);}
export default function Exports({notify}: {notify:Notify}) {
 const projects=useResource(()=>window.thean.projects.list(false),notify);const [projectId,setProjectId]=useState('');const [search,setSearch]=useState('');const [selected,setSelected]=useState<string[]>([]);const [date,setDate]=useState(localDate);const [preview,setPreview]=useState<ExportPreview|null>(null);const [warningOpen,setWarningOpen]=useState(false);const revision=useRef(0);const {busy,run}=useTask(notify);
 const employees=useResource(()=>projectId?window.thean.employees.list({projectId,includeArchived:false}):Promise.resolve([]),notify,[projectId]);
 const active=(employees.data??[]).filter(e=>e.projectId===projectId&&!e.archived);const filtered=active.filter(e=>matches(`${e.fullName} ${e.identityNumber}`,search));const chosen=selected.map(id=>active.find(e=>e.id===id)).filter((e):e is Employee=>!!e);
 const warnings=chosen.map(e=>({name:e.fullName||'Chưa ghi họ tên',missing:missingFields(e)})).filter(e=>e.missing.length);
 const invalidate=()=>{revision.current++;setPreview(null);setWarningOpen(false);};
 const choose=(ids:string[])=>{invalidate();setSelected(ids);};
 const changeProject=(id:string)=>{invalidate();setSelected([]);setProjectId(id);setSearch('');};
 useEffect(()=>{if(employees.loading)return;const valid=selected.filter(id=>active.some(e=>e.id===id));if(valid.length!==selected.length)choose(valid);},[employees.data,employees.loading]);
 useEffect(()=>()=>{revision.current++;},[]);
 const reorder=(index:number,delta:number)=>{const ids=[...selected];[ids[index],ids[index+delta]]=[ids[index+delta],ids[index]];choose(ids);};
 const createPreview=()=>{setWarningOpen(false);const requestRevision=revision.current;const request={projectId,employeeIds:[...selected],signingDate:date};void run(async()=>{const result=await window.thean.exports.preview(request);if(revision.current===requestRevision)setPreview(result);});};
 const save=(format:'docx'|'pdf'|'both')=>{if(!preview)return;void run(async()=>{const paths=await window.thean.exports.save(preview.token,format);notify(paths.length?`Đã lưu ${paths.length} tệp: ${paths.join(', ')}`:'Đã hủy lưu tệp.');});};
 return <><header className="page-head"><div><p className="eyebrow">TÀI LIỆU NHÂN SỰ</p><h1>Xuất lý lịch</h1><p>Chọn hồ sơ, sắp xếp thứ tự và xem trước trước khi lưu.</p></div></header>
 <div className="card export-controls"><Select label="Dự án xuất" value={projectId} disabled={busy} onChange={e=>changeProject(e.target.value)}><option value="">Chọn dự án</option>{projects.data?.filter(p=>!p.archived).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</Select><Field label="Ngày ký" type="date" required value={date} disabled={busy} onChange={e=>{invalidate();setDate(e.target.value);}}/><div className="export-note"><span className="badge">WORD + PDF</span><p>Ngày ký mặc định là ngày hôm nay trên máy tính.</p></div></div><LoadState {...projects} retry={projects.reload}/>
 {!projectId?<Empty title="Chọn dự án để xuất">Danh sách chỉ gồm nhân viên đang làm việc tại dự án đã chọn.</Empty>:<><div className="export-grid"><section className="card selection-card"><h2>Danh sách nhân viên</h2><Field label="Tìm nhân viên để xuất" type="search" value={search} disabled={busy} placeholder="Họ tên hoặc số căn cước" onChange={e=>setSearch(e.target.value)}/><div className="between selection-toolbar"><span className="muted">{filtered.length} kết quả</span><button disabled={busy||!filtered.length||employees.loading} onClick={()=>choose([...selected,...filtered.filter(e=>!selected.includes(e.id)).map(e=>e.id)])}>Chọn tất cả kết quả</button></div><LoadState {...employees} retry={employees.reload}/>{!employees.loading&&!employees.error&&filtered.length===0&&<p className="muted">Không có nhân viên phù hợp.</p>}<div className="selection-list">{filtered.map(e=><label className="select-person" key={e.id}><input type="checkbox" aria-label={`Chọn ${e.fullName}`} checked={selected.includes(e.id)} disabled={busy||employees.loading} onChange={event=>choose(event.target.checked?[...selected,e.id]:selected.filter(id=>id!==e.id))}/><span><strong>{e.fullName}</strong><small>{e.identityNumber||'Chưa ghi số căn cước'}</small></span>{missingFields(e).length>0&&<span className="badge yellow">Thiếu thông tin</span>}</label>)}</div></section>
 <section className="card selection-card"><div className="between"><h2>Thứ tự xuất</h2><span className="badge green">{selected.length} hồ sơ</span></div><p className="muted">Thứ tự bên dưới là thứ tự trong tài liệu.</p>{selected.length>0&&<button className="text-button" disabled={busy} onClick={()=>choose([])}>Bỏ chọn tất cả</button>}<ol className="ordered-list">{chosen.map((e,i)=><li key={e.id}><span className="order-number">{String(i+1).padStart(2,'0')}</span><strong>{e.fullName}</strong><div className="reorder"><button aria-label={`Đưa ${e.fullName} lên`} disabled={busy||i===0} onClick={()=>reorder(i,-1)}>↑</button><button aria-label={`Đưa ${e.fullName} xuống`} disabled={busy||i===chosen.length-1} onClick={()=>reorder(i,1)}>↓</button><button aria-label={`Bỏ chọn ${e.fullName}`} disabled={busy} onClick={()=>choose(selected.filter(id=>id!==e.id))}>×</button></div></li>)}</ol>{!selected.length&&<p className="muted">Chọn nhân viên ở danh sách bên trái.</p>}<div className="preview-action"><button className="primary" disabled={busy||employees.loading||!!employees.error||!projectId||!date||selected.length===0||chosen.length!==selected.length} onClick={()=>warnings.length?setWarningOpen(true):createPreview()}>{busy?'Đang xử lý…':'Xem trước PDF'}</button><p className="muted small">Chỉ xuất những hồ sơ đã chọn, theo đúng thứ tự.</p></div></section></div>
 {preview&&<section className="card pdf-preview"><div className="between"><div><h2>Bản xem trước</h2><p className="muted">{preview.employeeCount} hồ sơ · Ngày ký {date}</p></div><div className="inline-actions"><button disabled={busy} onClick={()=>save('docx')}>Lưu Word</button><button disabled={busy} onClick={()=>save('pdf')}>Lưu PDF</button><button className="primary" disabled={busy} onClick={()=>save('both')}>Lưu cả Word và PDF</button></div></div>{preview.warnings.length>0&&<div className="notice"><ul>{preview.warnings.map((w,i)=><li key={i}>{w}</li>)}</ul></div>}<iframe title="Bản xem trước lý lịch" src={preview.pdfUrl}/></section>}
 </>}
 {warningOpen&&<Confirm title="Hồ sơ chưa đầy đủ" busy={busy} action="Vẫn xem trước" onClose={()=>setWarningOpen(false)} onConfirm={createPreview}><p>Các hồ sơ sau còn thiếu thông tin. Bạn có thể tiếp tục xuất hoặc quay lại hoàn thiện hồ sơ.</p><ul className="warning-list">{warnings.map((w,i)=><li key={i}><strong>{w.name}</strong>: {w.missing.join(', ')}</li>)}</ul></Confirm>}
 </>;
}
