import React, { useEffect, useId, useRef, useState } from 'react';
import type { Asset, AssetKind } from '../../shared/types';
import { Field, Modal, type Notify, useTask, messageOf } from './ui';
type Rect = {x:number;y:number;width:number;height:number};
export function AssetImage({id,alt,className}: {id:string|null;alt:string;className?:string}) {
 const [url,setUrl]=useState('');const [failed,setFailed]=useState(false);
 useEffect(()=>{let active=true;setUrl('');setFailed(false);if(id) void window.thean.assets.get(id).then(a=>{if(active){setUrl(a?.url??'');setFailed(!a);}}).catch(()=>{if(active)setFailed(true);});return()=>{active=false;};},[id]);
 return url&&!failed?<img src={url} alt={alt} className={className} onError={()=>setFailed(true)}/>:<div className={`image-placeholder ${className??''}`}>{failed?'Không tải được ảnh':id?'Đang tải ảnh…':'Chưa có ảnh'}</div>;
}
export function ImageSlot({label,kind,id,onChange,notify,disabled=false,onBusy}: {label:string;kind:AssetKind;id:string|null;onChange:(id:string|null)=>void;notify:Notify;disabled?:boolean;onBusy?:(busy:boolean)=>void}) {
 const inputId=useId(); const {busy,run}=useTask(notify);const [editing,setEditing]=useState<Asset|null>(null);
 useEffect(()=>{onBusy?.(busy);},[busy]);
 const upload=async(file:File)=>{if(!['image/png','image/jpeg'].includes(file.type)){notify('Chỉ chọn ảnh PNG hoặc JPEG.',true);return;}if(file.size>20*1024*1024){notify('Ảnh quá lớn. Vui lòng chọn ảnh không quá 20 MB.',true);return;}await run(async()=>{const data=new Uint8Array(await file.arrayBuffer());const asset=await window.thean.assets.import(kind,data,file.name);onChange(asset.id);notify(`Đã tải ${label.toLocaleLowerCase('vi')}.`);});};
 return <section className={`image-slot ${kind==='portrait'?'portrait-slot':''}`}><h3>{label}</h3><AssetImage id={id} alt={label}/><div className="image-actions"><label className={`upload-button ${disabled||busy?'disabled':''}`} htmlFor={inputId}>{busy?'Đang tải…':id?'Thay ảnh':'Tải ảnh'}<input id={inputId} className="file-input" type="file" accept="image/png,image/jpeg" disabled={disabled||busy} aria-label={`Tải ${label}`} onChange={e=>{const file=e.currentTarget.files?.[0];e.currentTarget.value='';if(file)void upload(file);}}/></label>{id&&<><button type="button" disabled={disabled||busy} onClick={()=>void run(async()=>{const asset=await window.thean.assets.get(id);if(!asset)throw new Error('Không tìm thấy ảnh. Vui lòng tải lại.');setEditing(asset);})}>Cắt / xoay</button><button type="button" disabled={disabled||busy} aria-label={`Bỏ ${label}`} onClick={()=>onChange(null)}>Bỏ ảnh</button></>}</div>{editing&&<ImageEditor asset={editing} kind={kind} notify={notify} onClose={()=>setEditing(null)} onSave={assetId=>{onChange(assetId);setEditing(null);}}/>}</section>;
}
export function ImageEditor({asset,kind,notify,onClose,onSave}: {asset:Asset;kind:AssetKind;notify:Notify;onClose:()=>void;onSave:(id:string)=>void}) {
 const canvasRef=useRef<HTMLCanvasElement>(null);const [source,setSource]=useState<HTMLImageElement|null>(null);const [rotation,setRotation]=useState(0);const [crop,setCrop]=useState<Rect>({x:0,y:0,width:0,height:0});const [error,setError]=useState('');const drag=useRef<{x:number;y:number}|null>(null);const {busy,run}=useTask(notify);
 useEffect(()=>{let active=true;let ownedUrl:string|undefined;const image=new Image();
 image.onload=()=>{if(active){setSource(image);setCrop({x:0,y:0,width:image.naturalWidth,height:image.naturalHeight});}};
 image.onerror=()=>{if(active)setError('Không mở được ảnh để chỉnh sửa. Vui lòng tải lại ảnh.');};
 void fetch(asset.url).then(r=>{if(!r.ok)throw new Error('Không tải được ảnh.');return r.blob();}).then(blob=>{if(active){ownedUrl=URL.createObjectURL(blob);image.src=ownedUrl;}}).catch(e=>{if(active)setError(messageOf(e));});
 return()=>{active=false;image.onload=null;image.onerror=null;if(ownedUrl)URL.revokeObjectURL(ownedUrl);}; },[asset.url]);
 const width=source?(rotation%180===0?source.naturalWidth:source.naturalHeight):0;
 const height=source?(rotation%180===0?source.naturalHeight:source.naturalWidth):0;
 const draw=(target:HTMLCanvasElement)=>{if(!source)return;target.width=width;target.height=height;const ctx=target.getContext('2d');if(!ctx)throw new Error('Không mở được công cụ chỉnh ảnh.');ctx.translate(width/2,height/2);ctx.rotate(rotation*Math.PI/180);ctx.drawImage(source,-source.naturalWidth/2,-source.naturalHeight/2);ctx.setTransform(1,0,0,1,0,0);};
 useEffect(()=>{if(!source||!canvasRef.current)return;try{draw(canvasRef.current);const ctx=canvasRef.current.getContext('2d')!;if(crop.width&&crop.height){ctx.fillStyle='rgba(30,30,30,0.38)';ctx.beginPath();ctx.rect(0,0,width,height);ctx.rect(crop.x,crop.y,crop.width,crop.height);ctx.fill('evenodd');ctx.strokeStyle='#ffffff';ctx.lineWidth=Math.max(2,width/400);ctx.strokeRect(crop.x,crop.y,crop.width,crop.height);}}catch(e){setError(messageOf(e));}},[source,rotation,crop]);
 const point=(e:React.PointerEvent<HTMLCanvasElement>)=>{const rect=e.currentTarget.getBoundingClientRect();return{x:Math.max(0,Math.min(width,(e.clientX-rect.left)/rect.width*width)),y:Math.max(0,Math.min(height,(e.clientY-rect.top)/rect.height*height))};};
 const save=()=>void run(async()=>{if(!source||crop.width<1||crop.height<1)throw new Error('Vui lòng chọn vùng ảnh cần giữ.');const rotated=document.createElement('canvas');draw(rotated);const output=document.createElement('canvas');output.width=Math.max(1,Math.round(crop.width));output.height=Math.max(1,Math.round(crop.height));const ctx=output.getContext('2d');if(!ctx)throw new Error('Không xử lý được ảnh.');ctx.drawImage(rotated,crop.x,crop.y,crop.width,crop.height,0,0,output.width,output.height);const blob=await new Promise<Blob>((resolve,reject)=>output.toBlob(b=>b?resolve(b):reject(new Error('Không lưu được ảnh.')),'image/png'));const result=await window.thean.assets.import(kind,new Uint8Array(await blob.arrayBuffer()),`${asset.filename.replace(/\.[^.]+$/,'')}-edited.png`);onSave(result.id);notify('Đã lưu ảnh đã chỉnh.');});
 const coordinate=(key:keyof Rect,value:number)=>setCrop(c=>{const next={...c,[key]:Math.max(0,value)};next.x=Math.min(next.x,Math.max(0,width-1));next.y=Math.min(next.y,Math.max(0,height-1));next.width=Math.min(next.width,width-next.x);next.height=Math.min(next.height,height-next.y);return next;});
 return <Modal title="Cắt và xoay ảnh" onClose={onClose} busy={busy} wide><div className="modal-body"><p className="muted">Kéo trên ảnh để chọn vùng cần giữ, hoặc nhập kích thước bên dưới. Xoay ảnh trước khi cắt.</p>{error&&<p className="notice error" role="alert">{error}</p>}{!source&&!error&&<p role="status">Đang mở ảnh…</p>}<div className="canvas-wrap"><canvas ref={canvasRef} aria-label="Ảnh chỉnh sửa, kéo để chọn vùng cắt" onPointerDown={e=>{if(!source||busy)return;drag.current=point(e);e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(!drag.current)return;const p=point(e);setCrop({x:Math.min(drag.current.x,p.x),y:Math.min(drag.current.y,p.y),width:Math.abs(p.x-drag.current.x),height:Math.abs(p.y-drag.current.y)});}} onPointerUp={()=>{drag.current=null;}} onPointerCancel={()=>{drag.current=null;}}/></div><div className="crop-fields">{([['x','Vị trí ngang'],['y','Vị trí dọc'],['width','Chiều rộng'],['height','Chiều cao']] as const).map(([key,label])=><Field key={key} label={label} type="number" min={0} step={1} value={Math.round(crop[key])} disabled={!source||busy} onChange={e=>coordinate(key,Number(e.target.value))}/>)}</div><div className="inline-actions"><button type="button" disabled={!source||busy} onClick={()=>{setRotation(r=>(r+90)%360);setCrop({x:0,y:0,width:height,height:width});}}>Xoay 90°</button><button type="button" disabled={!source||busy} onClick={()=>setCrop({x:0,y:0,width,height})}>Giữ toàn bộ ảnh</button></div></div><footer className="actions"><button type="button" onClick={onClose} disabled={busy}>Hủy</button><button type="button" className="primary" disabled={!source||!!error||busy||crop.width<1||crop.height<1} onClick={save}>{busy?'Đang lưu…':'Lưu ảnh đã chỉnh'}</button></footer></Modal>;
}
