import React, { useState } from 'react';
import type { Project, ProjectInput } from '../../shared/types';
import { Confirm, Empty, Field, LoadState, Modal, TextArea, type Notify, useResource, useTask } from './ui';
const blank: ProjectInput = {code:'',name:'',location:'',notes:''};
export default function Projects({notify}: {notify:Notify}) {
 const [includeArchived,setIncludeArchived]=useState(false); const list=useResource(()=>window.thean.projects.list(includeArchived),notify,[includeArchived]);
 const [draft,setDraft]=useState<ProjectInput|null>(null);const [archive,setArchive]=useState<Project|null>(null);const {busy,run}=useTask(notify);
 const change=(key:keyof ProjectInput,value:string)=>setDraft(d=>d?{...d,[key]:value}:d);
 return <><header className="page-head"><div><p className="eyebrow">ĐỊA ĐIỂM LÀM VIỆC</p><h1>Dự án</h1><p>Quản lý dự án và nơi làm việc của nhân viên.</p></div><button className="primary" onClick={()=>setDraft({...blank})}>Thêm dự án</button></header>
 <div className="toolbar"><span className="muted">{list.data?.length ?? 0} dự án</span><label className="check"><input type="checkbox" checked={includeArchived} onChange={e=>setIncludeArchived(e.target.checked)}/>Hiện dự án lưu trữ</label></div>
 <LoadState {...list} retry={list.reload}/>
 {!list.loading&&!list.error&&list.data?.length===0&&<Empty title="Chưa có dự án">Thêm dự án đầu tiên để bắt đầu quản lý hồ sơ nhân sự.</Empty>}
 <div className="project-grid">{list.data?.map(p=><article className="card project-card" key={p.id}><div className="between"><span className="code">{p.code}</span><span className={`badge ${p.archived?'':'green'}`}>{p.archived?'Lưu trữ':'Đang hoạt động'}</span></div><h2>{p.name}</h2><p className="muted">{p.location||'Chưa ghi địa điểm'}</p><div className="project-count"><strong>{p.employeeCount}</strong><span>nhân viên hiện tại</span></div>{p.notes&&<p className="note-text">{p.notes}</p>}<footer className="card-actions"><button onClick={()=>setDraft({id:p.id,code:p.code,name:p.name,location:p.location,notes:p.notes,archived:p.archived})}>Sửa dự án</button>{!p.archived&&<button onClick={()=>setArchive(p)}>Lưu trữ</button>}</footer></article>)}</div>
 {draft&&<Modal title={draft.id?'Sửa dự án':'Thêm dự án'} onClose={()=>setDraft(null)} busy={busy}><form onSubmit={e=>{e.preventDefault();void run(async()=>{await window.thean.projects.save({...draft,code:draft.code.trim(),name:draft.name.trim()});setDraft(null);list.reload();notify('Đã lưu dự án.');});}}><fieldset disabled={busy}><div className="modal-body form-grid"><Field label="Mã dự án" required maxLength={40} value={draft.code} onChange={e=>change('code',e.target.value)}/><Field label="Tên dự án" required maxLength={200} value={draft.name} onChange={e=>change('name',e.target.value)}/><div className="span-2"><Field label="Địa điểm" value={draft.location} onChange={e=>change('location',e.target.value)}/></div><div className="span-2"><TextArea label="Ghi chú" value={draft.notes} onChange={e=>change('notes',e.target.value)}/></div>{draft.archived&&<label className="check span-2"><input type="checkbox" checked={draft.archived} onChange={e=>setDraft({...draft,archived:e.target.checked})}/>Lưu trữ dự án</label>}</div><footer className="actions"><button type="button" onClick={()=>setDraft(null)}>Hủy</button><button className="primary">{busy?'Đang lưu…':'Lưu dự án'}</button></footer></fieldset></form></Modal>}
 {archive&&<Confirm title="Lưu trữ dự án" busy={busy} onClose={()=>setArchive(null)} action="Xác nhận lưu trữ" onConfirm={()=>void run(async()=>{await window.thean.projects.archive(archive.id);setArchive(null);list.reload();notify('Đã lưu trữ dự án.');})}><p>Dự án <strong>{archive.name}</strong> sẽ được chuyển vào danh sách lưu trữ. Hồ sơ và lịch sử nhân viên vẫn được giữ lại.</p></Confirm>}
 </>;
}
