import React, { useEffect, useState } from 'react';
import type { CompanySettings } from '../../shared/types';
import { ImageSlot } from './Images';
import { Confirm, Field, LoadState, TextArea, type Notify, useResource, useTask } from './ui';
export default function Settings({notify,onRestore}: {notify:Notify;onRestore:()=>void}) {
 const settings=useResource(()=>window.thean.settings.get(),notify);const info=useResource(()=>window.thean.app.info(),notify);const [draft,setDraft]=useState<CompanySettings|null>(null);const [restore,setRestore]=useState(false);const [imageBusy,setImageBusy]=useState<Record<string,boolean>>({});const {busy,run}=useTask(notify);
 useEffect(()=>{if(settings.data)setDraft(settings.data);},[settings.data]);
 const locked=busy||Object.values(imageBusy).some(Boolean);const change=(key:keyof CompanySettings,value:string|null)=>setDraft(d=>d?{...d,[key]:value}:d);
 return <><header className="page-head"><div><p className="eyebrow">THIẾT LẬP ỨNG DỤNG</p><h1>Cấu hình</h1><p>Thông tin công ty, chữ ký và dữ liệu trên máy tính này.</p></div></header><LoadState {...settings} retry={settings.reload}/>
  {draft&&<form onSubmit={e=>{e.preventDefault();if(locked)return;void run(async()=>{const result=await window.thean.settings.save(draft);setDraft(result);notify('Đã lưu cấu hình công ty.');});}}><div className="settings-grid"><section className="card"><h2>Thông tin công ty</h2><p className="muted">Dùng ở đầu trang và phần ký trong tài liệu lý lịch.</p><fieldset disabled={busy}><div className="form-grid"><div className="span-2"><Field label="Tên công ty" required placeholder="Ví dụ: CÔNG TY CỔ PHẦN THẾ AN" value={draft.companyName} onChange={e=>change('companyName',e.target.value)}/></div><div className="span-2"><TextArea label="Địa chỉ công ty" placeholder="Địa chỉ trụ sở công ty (dùng trên tài liệu xuất)…" value={draft.address} onChange={e=>change('address',e.target.value)}/></div><Field label="Email" type="email" placeholder="Ví dụ: contact@thean.vn" value={draft.email} onChange={e=>change('email',e.target.value)}/><Field label="Địa điểm ký" placeholder="Ví dụ: Long An" value={draft.signingPlace} onChange={e=>change('signingPlace',e.target.value)}/><Field label="Bộ phận ký" placeholder="Ví dụ: GIÁM ĐỐC hoặc PHÒNG NHÂN SỰ" value={draft.signingDepartment} onChange={e=>change('signingDepartment',e.target.value)}/><Field label="Người ký" placeholder="Ví dụ: Nguyễn Văn A" value={draft.signerName} onChange={e=>change('signerName',e.target.value)}/></div></fieldset></section><section className="card settings-images"><h2>Nhận diện và chữ ký</h2><ImageSlot label="Logo công ty" kind="logo" id={draft.logoId} onChange={id=>change('logoId',id)} notify={notify} disabled={locked} onBusy={b=>setImageBusy(s=>({...s,logo:b}))}/><ImageSlot label="Ảnh chữ ký" kind="signature" id={draft.signatureId} onChange={id=>change('signatureId',id)} notify={notify} disabled={locked} onBusy={b=>setImageBusy(s=>({...s,signature:b}))}/></section></div><div className="settings-save"><button className="primary" disabled={locked}>{busy?'Đang xử lý…':'Lưu cấu hình'}</button></div></form>}
 <section className="card data-settings"><div><h2>Dữ liệu và sao lưu</h2><p className="muted">Dữ liệu lưu cục bộ. Sao lưu định kỳ để giữ an toàn hồ sơ và ảnh.</p><LoadState {...info} retry={info.reload}/>{info.data&&<dl><div><dt>Phiên bản</dt><dd>{info.data.version}</dd></div><div><dt>Thư mục dữ liệu</dt><dd className="code path">{info.data.dataDirectory}</dd></div></dl>}</div><div className="data-actions"><button disabled={locked} onClick={()=>void run(async()=>{await window.thean.app.openDataDirectory();})}>Mở thư mục dữ liệu</button><button disabled={locked} onClick={()=>void run(async()=>{const path=await window.thean.backup.create();notify(path?`Đã tạo bản sao lưu: ${path}`:'Đã hủy sao lưu.');})}>Tạo bản sao lưu</button><button disabled={locked} onClick={()=>setRestore(true)}>Khôi phục dữ liệu</button></div></section>
 {restore&&<Confirm title="Khôi phục dữ liệu" busy={busy} onClose={()=>setRestore(false)} action="Chọn bản sao lưu và khôi phục" onConfirm={()=>void run(async()=>{const restored=await window.thean.backup.restore();setRestore(false);if(restored){notify('Đã khôi phục dữ liệu. Các danh sách đã được cập nhật.');onRestore();settings.reload();info.reload();}else notify('Đã hủy khôi phục.');})}><p>Khôi phục sẽ thay thế dữ liệu hiện tại bằng dữ liệu trong bản sao lưu đã chọn, bao gồm hồ sơ, dự án, ảnh và cấu hình.</p><p>Hãy tạo một bản sao lưu hiện tại trước khi tiếp tục nếu cần giữ lại dữ liệu đang có.</p></Confirm>}
 </>;
}
